name = "cal-availability-checker"
main = "src/index.ts"
compatibility_date = "2024-10-29"

[vars]
DEFAULT_FLEXIBILITY_HOURS = "2"
DEFAULT_DURATION_MINUTES = "30"
CAL_API_URL = "https://api.cal.com/v2"

# Add your secrets via:
# wrangler secret put ANTHROPIC_API_KEY
# wrangler secret put CAL_API_KEY
